INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Tuscaloosa', 'Cambridge', '35487', 82);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Birmingham', 'Bultman', '35242', 226);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Birmingham', 'Nova', '35263', 634);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Tuscaloosa', 'Talmadge', '35487', 9);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Birmingham', 'Dapin', '35215', 704);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Mobile', 'Rusk', '36689', 15);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Huntsville', 'Derek', '35805', 2190);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Anniston', 'Sommers', '36205', 8848);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Mobile', 'Di Loreto', '36610', 4103);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Anniston', 'Mariners Cove', '36205', 55594);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Mobile', 'Derek', '36610', 3208);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Montgomery', 'Weeping Birch', '36114', 6005);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Birmingham', 'Green', '35254', 6212);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Mobile', 'Burrows', '36670', 41);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Birmingham', 'Darwin', '35215', 8);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Birmingham', 'Carberry', '35231', 6227);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Montgomery', 'Springs', '36125', 26);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Montgomery', 'Kenwood', '36109', 789);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Birmingham', 'Longview', '35290', 52);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Mobile', 'Goodland', '36616', 2);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Anniston', 'Gulseth', '36205', 936);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Birmingham', 'Pepper Wood', '35242', 83);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Montgomery', 'Fairfield', '36119', 4);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Birmingham', 'Cambridge', '35205', 53);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Anniston', 'Sundown', '36205', 1);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Birmingham', 'Harbort', '35244', 56249);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Montgomery', 'Maple', '36195', 80);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alabama', 'Huntsville', 'Petterle', '35895', 44177);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alaska', 'Anchorage', 'Coleman', '99599', 2);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Alaska', 'Anchorage', 'Sundown', '99599', 12);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Tucson', 'Elmside', '85754', 32);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Tucson', 'Comanche', '85705', 0);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Phoenix', 'Tomscot', '85040', 556);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Phoenix', 'Delladonna', '85045', 4);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Tempe', 'Arapahoe', '85284', 4792);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Mesa', 'Judy', '85205', 862);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Tucson', 'Dapin', '85705', 5314);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Tucson', 'Acker', '85705', 1);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Chandler', 'Laurel', '85246', 8812);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Tempe', 'Basil', '85284', 29);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Glendale', 'Harbort', '85311', 77688);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Phoenix', 'Village', '85005', 3);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arizona', 'Phoenix', 'Cody', '85030', 23419);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arkansas', 'North Little Rock', 'Main', '72199', 12);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arkansas', 'North Little Rock', 'Di Loreto', '72199', 7);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arkansas', 'North Little Rock', 'Bayside', '72199', 3511);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arkansas', 'Little Rock', 'Brown', '72222', 9374);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arkansas', 'North Little Rock', 'Rieder', '72118', 982);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arkansas', 'Fort Smith', 'Ilene', '72905', 1857);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('Arkansas', 'North Little Rock', 'Anniversary', '72118', 90076);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Diego', 'Monument', '92145', 399);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Bernardino', 'Blaine', '92410', 74399);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Palmdale', 'Anhalt', '93591', 0);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Newport Beach', 'Scott', '92662', 4772);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Jose', 'Main', '95128', 44080);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Ventura', 'Spaight', '93005', 56);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Bernardino', 'Oakridge', '92405', 43);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Diego', 'Utah', '92153', 2130);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Palo Alto', 'Butternut', '94302', 5587);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Van Nuys', 'Lindbergh', '91411', 31444);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Pasadena', 'Basil', '91109', 55);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Fresno', 'Talmadge', '93721', 64123);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Los Angeles', 'Fremont', '90071', 7);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Pasadena', 'Corry', '91186', 350);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Irvine', 'Ohio', '92612', 33);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Bernardino', 'Knutson', '92405', 94231);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Lerdahl', '94207', 36456);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Modesto', 'Loeprich', '95354', 8791);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Los Angeles', 'Melody', '90087', 36);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Van Nuys', 'Sachs', '91406', 0);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Jose', 'Ilene', '95113', 87316);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Los Angeles', 'Del Sol', '90055', 8);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Inglewood', 'Melby', '90305', 443);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Los Angeles', 'Lyons', '90020', 23);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sunnyvale', 'Fisk', '94089', 58);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Los Angeles', 'Oakridge', '90015', 34);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Newport Beach', 'Del Sol', '92662', 2421);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Long Beach', 'Eagle Crest', '90840', 4);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Simi Valley', 'Pierstorff', '93094', 138);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Garden Grove', '5th', '92645', 5977);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Hayward', 'Talmadge', '94544', 3);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Warner', '94245', 3857);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Los Angeles', 'Northport', '90060', 6);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Los Angeles', 'Waywood', '90005', 97);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Fairview', '94286', 1986);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Orange', 'Buhler', '92862', 73523);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Lakewood Gardens', '94230', 29);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Wayridge', '95833', 9);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Cambridge', '94297', 218);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Santa Barbara', 'Burrows', '93150', 34971);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Irvine', '5th', '92717', 9);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Diego', 'Fremont', '92153', 84);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'South Lake Tahoe', 'Hazelcrest', '96154', 181);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Maple', '94207', 0);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Huntington Beach', 'Burrows', '92648', 8053);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Bakersfield', 'Dovetail', '93381', 22617);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Huntington Beach', 'Jenifer', '92648', 62);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Los Angeles', 'Morningstar', '90045', 0);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Diego', 'Stuart', '92137', 71);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Modesto', 'Rutledge', '95397', 9);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Pasadena', 'Bellgrove', '91199', 5);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Corona', 'Mayer', '92878', 946);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'South Lake Tahoe', 'Monica', '96154', 7);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Orange', 'Garrison', '92668', 2);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Santa Clara', 'Oakridge', '95054', 0);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Torrance', 'Moland', '90510', 78);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Diego', 'Wayridge', '92145', 42);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Van Nuys', 'Hallows', '91406', 3);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Orange', 'Eliot', '92867', 81561);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Francisco', 'Fremont', '94164', 860);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Fullerton', 'Grover', '92835', 6208);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Los Angeles', 'Mallory', '90025', 20);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'North Hollywood', 'Algoma', '91616', 81885);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Butternut', '94230', 4696);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Francisco', 'Prentice', '94147', 3);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Fresno', 'Fisk', '93709', 72);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Torrance', 'Columbus', '90510', 9276);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Mountain View', 'Texas', '94042', 46);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Irvine', 'Declaration', '92619', 85312);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Orange', 'Kedzie', '92668', 7897);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Pepper Wood', '94297', 2);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Anaheim', 'Cottonwood', '92805', 9);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Santa Barbara', 'Roth', '93106', 21);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Francisco', 'Continental', '94105', 21);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Luis Obispo', 'Warrior', '93407', 71);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Long Beach', 'Rusk', '90847', 9483);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Bernardino', 'Utah', '92415', 3740);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Chula Vista', 'Independence', '91913', 63983);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Chula Vista', 'Sutherland', '91913', 6560);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Petaluma', 'Lien', '94975', 3588);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Los Angeles', 'Ruskin', '90025', 29573);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Inglewood', 'Michigan', '90398', 56687);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Hayward', 'Norway Maple', '94544', 33);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Irvine', 'Roxbury', '92612', 62858);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Lancaster', 'Express', '93584', 6);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Whittier', 'School', '90610', 848);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sunnyvale', 'Hoepker', '94089', 4);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Riverside', 'Veith', '92519', 8);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Mountain View', 'Dahle', '94042', 85356);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Jose', 'Hazelcrest', '95138', 70);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Oakland', '5th', '94622', 929);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Fresno', 'Mandrake', '93715', 8);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Pomona', 'Sunbrook', '91797', 9745);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Los Angeles', 'Claremont', '90076', 7);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Escondido', 'Hooker', '92030', 65);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Glendale', 'Hovde', '91205', 61);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Oakland', 'Fair Oaks', '94605', 8);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Los Angeles', 'Schlimgen', '90071', 325);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Diego', 'Veith', '92115', 48);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Concord', 'Birchwood', '94522', 5);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Newport Beach', 'Clemons', '92662', 7102);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Heath', '95865', 63490);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Modesto', 'Acker', '95354', 2734);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Karstens', '94263', 145);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Jose', 'Linden', '95155', 1);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Francisco', 'Northland', '94137', 84);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Chula Vista', 'Old Gate', '91913', 44);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Bernardino', 'Gulseth', '92405', 87);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Colorado', '94250', 5687);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'Sacramento', 'Anderson', '94263', 29);
INSERT INTO public."Indirizzo" (regione, città, via, provincia, numero_civico) VALUES ('California', 'San Francisco', 'Loeprich', '94116', 5);
