INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (1, 'FastTrack Express', 9, 'ddaffewfew');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (2, 'SwiftShip', 13.9, 'Sprain of calcaneofibular ligament of right ankle, sequela');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (3, 'RapidCargo', 2.8, 'Unsp injury of unspecified middle and inner ear, subs encntr');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (4, 'SpeedyDeliver', 7.9, 'Nondisp fx of olecran pro w intartic extn unsp ulna, 7thB');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (5, 'QuickDispatch', 15.9, 'Other meniscus derangements, unsp meniscus, right knee');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (6, 'TurboTransit', 8.9, 'Breakdown (mechanical) of implnt elec nstim, generator');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (7, 'ExpressMovers', 12.1, 'Corrosion of unsp degree of left shoulder, subs encntr');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (8, 'LightningLogistics', 3.5, 'Other instability, ankle and foot');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (9, 'SpeedwayShipping', 7.6, 'Mature T/NK-cell lymphomas, unsp, intrapelvic lymph nodes');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (10, 'RapidConnect', 17.2, 'Oth spon disrupt of anterior cruciate ligament of right knee');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (11, 'SwiftHaul', 7.4, 'Gestational diabetes mellitus in childbirth, unsp control');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (12, 'InstantDelivery', 7.8, 'Medial dislocation of left ulnohumeral joint, subs encntr');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (13, 'RapidRoute', 16.3, 'Nondisp oblique fx shaft of l rad, 7thJ');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (14, 'ExpressLink', 9, 'Acquired absence of unspecified shoulder');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (15, 'QuickShip', 15.9, 'Physeal arrest, humerus, unspecified');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (16, 'SpeedyFreight', 14.9, 'Puncture wound with foreign body of unsp shoulder, sequela');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (17, 'TurboCargo', 10.5, 'Prsn outsd 3-whl mv inj in clsn w statnry obj nontraf, sqla');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (18, 'VelocityExpress', 12.6, 'Nondisp fx of medial phalanx of r mid fngr, init for opn fx');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (19, 'FastLaneLogistics', 15.9, 'Colles'' fx left rad, subs for opn fx type 3A/B/C w nonunion');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (20, 'RapidShip', 17.3, 'Contusion of right ear, subsequent encounter');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (21, 'SwiftTrans', 2.4, 'Lac w fb of lower back and pelvis w penet retroperiton, subs');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (22, 'ExpressSpeed', 16.5, 'Osteitis condensans, shoulder');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (23, 'QuickMove', 10, 'Unsp inj intrinsic musc/fasc/tend r mid finger at wrs/hnd lv');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (24, 'SpeedyDispatch', 14.7, 'Adhes due to fb acc left in body fol unsp procedure, sequela');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (25, 'RapidLogistics', 3.2, 'Puncture wound with foreign body of left wrist');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (26, 'SwiftDelivery', 3.2, 'Nondisp spiral fx shaft of r femr, 7thC');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (27, 'LightningExpress', 13.3, 'Nondisp suprcndl fx w intrcndl extn low end r femr, 7thR');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (28, 'SpeedwayLogistics', 7.8, 'Toxic effect of harmful algae and algae toxins, undet, subs');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (29, 'TurboTransport', 16.9, 'Wear of artic bearing surface of internal prosth l hip jt');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (30, 'FastTrackShipping', 4.2, 'Corros first deg of shldr/up lmb, ex wrs/hnd unsp site, subs');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (31, 'RapidConnect', 19.3, 'Unsp injury of intrinsic msl/tnd at ank/ft level, right foot');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (32, 'ExpressMovers', 16.3, 'Nondisp fx of neck of MC bone, subs for fx w nonunion');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (33, 'QuickTransit', 13.6, 'Colles'' fracture of unsp radius, subs for clos fx w malunion');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (34, 'SpeedyDeliver', 19.4, 'Toxic effect of contact w venomous frog, accidental, init');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (35, 'SwiftCargo', 12.6, '2-part nondisp fx of surg nk of unsp humer, 7thG');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (36, 'LightningLogistics', 16, 'Oth fracture of T9-T10 vertebra, subs for fx w nonunion');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (37, 'RapidRoute', 19.6, 'Adverse effect of local astringents/detergents, subs');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (38, 'ExpressLink', 13.6, 'Other spacecraft accident injuring occupant, init encntr');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (39, 'SpeedyShip', 4.1, 'Poisoning by expectorants, intentional self-harm, sequela');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (40, 'QuickHaul', 5.1, 'Unsp inj unsp musc/tend at lower leg level, left leg, subs');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (41, 'TurboDelivery', 5.9, 'Medial dislocation of left ulnohumeral joint');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (42, 'VelocityExpress', 11.4, 'Unsp superficial injury of left ring finger, subs encntr');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (43, 'FastLaneTransit', 12, 'Other specified disorders of synovium and tendon');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (44, 'RapidShip', 4, 'Corrosion of unsp degree of unsp scapular region, subs');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (45, 'SwiftFreight', 4.8, 'Other hypertrophic disorders of the skin');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (46, 'InstantConnect', 9.8, 'Multiple endocrine neoplasia [MEN] syndromes');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (47, 'SpeedyLogistics', 11.5, 'Drug/chem diab w prolif diab rtnop w trctn dtch macula,l eye');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (48, 'TurboTrans', 18, 'Disp fx of lateral cuneiform of l ft, 7thD');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (49, 'RapidSpeed', 13.2, 'Disp fx of dist phalanx of r mid fngr, 7thD');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (50, 'ExpressDispatch', 14.3, 'Separation of retinal layers');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (51, 'QuickShip', 6.4, 'Central European tick-borne encephalitis');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (52, 'SpeedyRoute', 10.8, 'Unspecified subluxation of left sternoclavicular joint');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (53, 'RapidLogistics', 1.1, 'Unspecified acquired deformity of forearm');
INSERT INTO public."Servizi" (id, nome, costo, descrizione) VALUES (54, 'SwiftDelivery', 10.8, 'Other recurrent atlantoaxial dislocation');
