INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (2, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (1, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (4, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (3, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (5, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (6, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (8, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (7, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (10, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (9, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (12, 6, 'TurboTransit', 8.9);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (11, 6, 'TurboTransit', 8.9);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (13, 7, 'ExpressMovers', 12.1);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (14, 7, 'ExpressMovers', 12.1);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (16, 8, 'LightningLogistics', 3.5);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (15, 8, 'LightningLogistics', 3.5);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (17, 9, 'SpeedwayShipping', 7.6);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (18, 9, 'SpeedwayShipping', 7.6);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (19, 10, 'RapidConnect', 17.2);
INSERT INTO public."Spedizione_Premium_Servizi" (tracking, id, nome_servizio, costo) VALUES (20, 10, 'RapidConnect', 17.2);
