INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (4, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (2, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (5, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (6, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (3, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (1, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (7, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (10, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (11, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (8, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (12, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (9, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (17, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (16, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (15, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (13, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (18, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (14, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (24, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (23, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (19, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (22, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (21, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (20, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (27, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (28, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (29, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (25, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (26, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (32, 6, 'TurboTransit', 8.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (34, 6, 'TurboTransit', 8.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (31, 6, 'TurboTransit', 8.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (30, 6, 'TurboTransit', 8.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (33, 6, 'TurboTransit', 8.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (36, 7, 'ExpressMovers', 12.1);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (38, 7, 'ExpressMovers', 12.1);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (35, 7, 'ExpressMovers', 12.1);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (39, 7, 'ExpressMovers', 12.1);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (37, 7, 'ExpressMovers', 12.1);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (44, 8, 'LightningLogistics', 3.5);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (40, 8, 'LightningLogistics', 3.5);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (42, 8, 'LightningLogistics', 3.5);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (41, 8, 'LightningLogistics', 3.5);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (43, 8, 'LightningLogistics', 3.5);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (47, 9, 'SpeedwayShipping', 7.6);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (46, 9, 'SpeedwayShipping', 7.6);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (45, 9, 'SpeedwayShipping', 7.6);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (49, 9, 'SpeedwayShipping', 7.6);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (48, 9, 'SpeedwayShipping', 7.6);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (52, 10, 'RapidConnect', 17.2);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (50, 10, 'RapidConnect', 17.2);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (51, 10, 'RapidConnect', 17.2);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (53, 10, 'RapidConnect', 17.2);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (54, 10, 'RapidConnect', 17.2);
