INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Tucson', 'Acker', '85705', 1, 'uajvuh30u29g422t');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Garden Grove', '5th', '92645', 5977, 'abogvl97e41a631n');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Mobile', 'Di Loreto', '36610', 4103, 'hmozuk35y60c790g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Butternut', '94230', 4696, 'oobxgl21n86l160z');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arkansas', 'Little Rock', 'Brown', '72222', 9374, 'ceecog34d09y094c');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Fresno', 'Mandrake', '93715', 8, 'corzss57a06d644t');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Los Angeles', 'Morningstar', '90045', 0, 'mlnxnc18l24m114u');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Los Angeles', 'Fremont', '90071', 7, 'aunxad02p33x402h');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Birmingham', 'Bultman', '35242', 226, 'kqwjjd23e43o622b');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Inglewood', 'Michigan', '90398', 56687, 'moqyaa96b41w621l');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Pomona', 'Sunbrook', '91797', 9745, 'kqupzq92g24n430p');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Fresno', 'Talmadge', '93721', 64123, 'hmozuk35y60c790g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Ventura', 'Spaight', '93005', 56, 'auaggp09y68t935y');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Los Angeles', 'Schlimgen', '90071', 325, 'vrrrzs98x58u998j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'North Hollywood', 'Algoma', '91616', 81885, 'ffdwee60s61t235w');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Corona', 'Mayer', '92878', 946, 'pvilho11h32q211g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Mobile', 'Derek', '36610', 3208, 'yiblfs65g56k279q');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Los Angeles', 'Claremont', '90076', 7, 'uajvuh30u29g422t');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Tuscaloosa', 'Cambridge', '35487', 82, 'biracl27s20m759i');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Long Beach', 'Eagle Crest', '90840', 4, 'rbxbrf79f09c376r');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Montgomery', 'Kenwood', '36109', 789, 'bucims80t97w944z');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Jose', 'Linden', '95155', 1, 'pvilho11h32q211g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Jose', 'Hazelcrest', '95138', 70, 'pvgfaf41e99l262m');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sunnyvale', 'Hoepker', '94089', 4, 'magujx74u13t692j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Anaheim', 'Cottonwood', '92805', 9, 'qabkgx49q61o993x');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Torrance', 'Columbus', '90510', 9276, 'yiblfs65g56k279q');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Fresno', 'Fisk', '93709', 72, 'aunxad02p33x402h');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Santa Clara', 'Oakridge', '95054', 0, 'utoxrt14i21h422h');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sunnyvale', 'Fisk', '94089', 58, 'arllpa74i66y238j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Pasadena', 'Bellgrove', '91199', 5, 'spjzpv06b62d022v');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Simi Valley', 'Pierstorff', '93094', 138, 'moqyaa96b41w621l');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Wayridge', '95833', 9, 'qmogjf57a26v287q');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arkansas', 'North Little Rock', 'Main', '72199', 12, 'qssbjx39t46r976n');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Maple', '94207', 0, 'vmrlhf74f78j242r');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Mesa', 'Judy', '85205', 862, 'corzss57a06d644t');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Modesto', 'Rutledge', '95397', 9, 'ceecog34d09y094c');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arkansas', 'Fort Smith', 'Ilene', '72905', 1857, 'pvilho11h32q211g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arkansas', 'North Little Rock', 'Rieder', '72118', 982, 'spjzpv06b62d022v');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Van Nuys', 'Sachs', '91406', 0, 'psfiod09k77a681u');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Tucson', 'Elmside', '85754', 32, 'magujx74u13t692j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Los Angeles', 'Melody', '90087', 36, 'qabkgx49q61o993x');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Birmingham', 'Dapin', '35215', 704, 'dvqwpq82d12u044j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Pasadena', 'Corry', '91186', 350, 'yiblfs65g56k279q');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Newport Beach', 'Clemons', '92662', 7102, 'mlnxnc18l24m114u');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Diego', 'Utah', '92153', 2130, 'dvqwpq82d12u044j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Van Nuys', 'Lindbergh', '91411', 31444, 'ffdwee60s61t235w');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Pasadena', 'Basil', '91109', 55, 'oobxgl21n86l160z');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alaska', 'Anchorage', 'Coleman', '99599', 2, 'rcjgxa50z51h696w');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Heath', '95865', 63490, 'bvsues78b56y479m');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Newport Beach', 'Scott', '92662', 4772, 'biracl27s20m759i');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Los Angeles', 'Waywood', '90005', 97, 'magujx74u13t692j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Bakersfield', 'Dovetail', '93381', 22617, 'mumnbw95f77i705t');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Irvine', 'Roxbury', '92612', 62858, 'pqjbjt76t60z084a');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Birmingham', 'Darwin', '35215', 8, 'echxll47x25b400a');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Francisco', 'Prentice', '94147', 3, 'hmozuk35y60c790g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Tempe', 'Arapahoe', '85284', 4792, 'qmogjf57a26v287q');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Huntington Beach', 'Jenifer', '92648', 62, 'qssbjx39t46r976n');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Oakland', 'Fair Oaks', '94605', 8, 'vmrlhf74f78j242r');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Hayward', 'Norway Maple', '94544', 33, 'abogvl97e41a631n');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Inglewood', 'Melby', '90305', 443, 'hhwjqv17k50w410f');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Irvine', 'Declaration', '92619', 85312, 'npyljq01s77p500h');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Irvine', 'Ohio', '92612', 33, 'jqkjfd25s12j468w');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Phoenix', 'Village', '85005', 3, 'vrrrzs98x58u998j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Karstens', '94263', 145, 'spjzpv06b62d022v');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Bernardino', 'Knutson', '92405', 94231, 'npyljq01s77p500h');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Chula Vista', 'Independence', '91913', 63983, 'arllpa74i66y238j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Anniston', 'Sommers', '36205', 8848, 'oobxgl21n86l160z');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Jose', 'Main', '95128', 44080, 'kqwjjd23e43o622b');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Modesto', 'Acker', '95354', 2734, 'ceecog34d09y094c');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Diego', 'Veith', '92115', 48, 'mumnbw95f77i705t');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Chula Vista', 'Old Gate', '91913', 44, 'biracl27s20m759i');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Cambridge', '94297', 218, 'corzss57a06d644t');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Los Angeles', 'Northport', '90060', 6, 'shnnfp42x22u151r');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Van Nuys', 'Hallows', '91406', 3, 'kqwjjd23e43o622b');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Tuscaloosa', 'Talmadge', '35487', 9, 'kjnlji67m42p786g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Hayward', 'Talmadge', '94544', 3, 'pqjbjt76t60z084a');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Birmingham', 'Green', '35254', 6212, 'npyljq01s77p500h');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Montgomery', 'Fairfield', '36119', 4, 'ikwfcz18b86e682q');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Los Angeles', 'Oakridge', '90015', 34, 'ikwfcz18b86e682q');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Birmingham', 'Cambridge', '35205', 53, 'fgceut14h98h226r');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Anniston', 'Sundown', '36205', 1, 'rbxbrf79f09c376r');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Lakewood Gardens', '94230', 29, 'pvgfaf41e99l262m');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Mountain View', 'Texas', '94042', 46, 'jqkjfd25s12j468w');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Whittier', 'School', '90610', 848, 'shnnfp42x22u151r');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Los Angeles', 'Ruskin', '90025', 29573, 'rbxbrf79f09c376r');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Anniston', 'Gulseth', '36205', 936, 'mfbslr80u19a742g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Oakland', '5th', '94622', 929, 'qmogjf57a26v287q');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Santa Barbara', 'Roth', '93106', 21, 'psfiod09k77a681u');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Montgomery', 'Springs', '36125', 26, 'psfiod09k77a681u');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Riverside', 'Veith', '92519', 8, 'dbhyzt20x58r774v');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Mobile', 'Goodland', '36616', 2, 'hhwjqv17k50w410f');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Phoenix', 'Cody', '85030', 23419, 'mumnbw95f77i705t');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Concord', 'Birchwood', '94522', 5, 'qssbjx39t46r976n');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Montgomery', 'Weeping Birch', '36114', 6005, 'jqkjfd25s12j468w');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Bernardino', 'Utah', '92415', 3740, 'mfbslr80u19a742g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Huntsville', 'Derek', '35805', 2190, 'ffdwee60s61t235w');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arkansas', 'North Little Rock', 'Di Loreto', '72199', 7, 'mlnxnc18l24m114u');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Warner', '94245', 3857, 'rcjgxa50z51h696w');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Lerdahl', '94207', 36456, 'awuyzn61c17c890d');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Diego', 'Wayridge', '92145', 42, 'biracl27s20m759i');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Orange', 'Buhler', '92862', 73523, 'tzrppf44x01q376h');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Chandler', 'Laurel', '85246', 8812, 'fdzdby16w16j502a');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Diego', 'Fremont', '92153', 84, 'fdzdby16w16j502a');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Birmingham', 'Harbort', '35244', 56249, 'moqyaa96b41w621l');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Birmingham', 'Nova', '35263', 634, 'auaggp09y68t935y');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Anniston', 'Mariners Cove', '36205', 55594, 'aunxad02p33x402h');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Santa Barbara', 'Burrows', '93150', 34971, 'kqupzq92g24n430p');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Modesto', 'Loeprich', '95354', 8791, 'echxll47x25b400a');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Los Angeles', 'Mallory', '90025', 20, 'cvjlwx09n81j993j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Francisco', 'Northland', '94137', 84, 'ocwhrd88a63g175v');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Fullerton', 'Grover', '92835', 6208, 'dvqwpq82d12u044j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Newport Beach', 'Del Sol', '92662', 2421, 'fgceut14h98h226r');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Bernardino', 'Blaine', '92410', 74399, 'utoxrt14i21h422h');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Palo Alto', 'Butternut', '94302', 5587, 'cvjlwx09n81j993j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Irvine', '5th', '92717', 9, 'uajvuh30u29g422t');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Glendale', 'Hovde', '91205', 61, 'ldaacb32t23p035n');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arkansas', 'North Little Rock', 'Anniversary', '72118', 90076, 'ocwhrd88a63g175v');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Diego', 'Stuart', '92137', 71, 'bvsues78b56y479m');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Phoenix', 'Tomscot', '85040', 556, 'tzrppf44x01q376h');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Jose', 'Ilene', '95113', 87316, 'bucims80t97w944z');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Mountain View', 'Dahle', '94042', 85356, 'tzrppf44x01q376h');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Birmingham', 'Pepper Wood', '35242', 83, 'arllpa74i66y238j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alaska', 'Anchorage', 'Sundown', '99599', 12, 'shnnfp42x22u151r');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Orange', 'Kedzie', '92668', 7897, 'awuyzn61c17c890d');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Huntington Beach', 'Burrows', '92648', 8053, 'vrrrzs98x58u998j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Los Angeles', 'Del Sol', '90055', 8, 'tamsxh39j08d107q');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Tucson', 'Comanche', '85705', 0, 'dbhyzt20x58r774v');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Tempe', 'Basil', '85284', 29, 'ldaacb32t23p035n');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Birmingham', 'Carberry', '35231', 6227, 'qabkgx49q61o993x');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Los Angeles', 'Lyons', '90020', 23, 'mfbslr80u19a742g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Fairview', '94286', 1986, 'dbhyzt20x58r774v');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Bernardino', 'Gulseth', '92405', 87, 'kqwjjd23e43o622b');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Francisco', 'Continental', '94105', 21, 'bucims80t97w944z');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Tucson', 'Dapin', '85705', 5314, 'kqupzq92g24n430p');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'South Lake Tahoe', 'Hazelcrest', '96154', 181, 'ldaacb32t23p035n');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Francisco', 'Loeprich', '94116', 5, 'dvqwpq82d12u044j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Lancaster', 'Express', '93584', 6, 'rcjgxa50z51h696w');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Torrance', 'Moland', '90510', 78, 'trepgg69u19k071g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Phoenix', 'Delladonna', '85045', 4, 'pvgfaf41e99l262m');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Huntsville', 'Petterle', '35895', 44177, 'pqjbjt76t60z084a');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Petaluma', 'Lien', '94975', 3588, 'fgceut14h98h226r');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arkansas', 'North Little Rock', 'Bayside', '72199', 3511, 'bvsues78b56y479m');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Luis Obispo', 'Warrior', '93407', 71, 'tamsxh39j08d107q');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Orange', 'Garrison', '92668', 2, 'nxrwjy67e78k983a');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Mobile', 'Burrows', '36670', 41, 'awuyzn61c17c890d');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Palmdale', 'Anhalt', '93591', 0, 'trepgg69u19k071g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Long Beach', 'Rusk', '90847', 9483, 'hhwjqv17k50w410f');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Mobile', 'Rusk', '36689', 15, 'cvjlwx09n81j993j');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Escondido', 'Hooker', '92030', 65, 'fdzdby16w16j502a');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Orange', 'Eliot', '92867', 81561, 'auaggp09y68t935y');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Montgomery', 'Maple', '36195', 80, 'abogvl97e41a631n');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Arizona', 'Glendale', 'Harbort', '85311', 77688, 'vmrlhf74f78j242r');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Anderson', '94263', 29, 'kjnlji67m42p786g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Colorado', '94250', 5687, 'auaggp09y68t935y');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Diego', 'Monument', '92145', 399, 'nxrwjy67e78k983a');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('Alabama', 'Birmingham', 'Longview', '35290', 52, 'tamsxh39j08d107q');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Chula Vista', 'Sutherland', '91913', 6560, 'ikwfcz18b86e682q');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'Sacramento', 'Pepper Wood', '94297', 2, 'echxll47x25b400a');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'South Lake Tahoe', 'Monica', '96154', 7, 'ocwhrd88a63g175v');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Francisco', 'Fremont', '94164', 860, 'kjnlji67m42p786g');
INSERT INTO public."Indirizzo_Utente" (regione, città, via, provincia, numero_civico, "User") VALUES ('California', 'San Bernardino', 'Oakridge', '92405', 43, 'kjnlji67m42p786g');
