INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (1, 'Washington', 'Seattle', 'Dawn', '98148', 5);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (2, 'Florida', 'Clearwater', 'Corry', '33758', 358);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (3, 'Massachusetts', 'Waltham', 'Jana', '02453', 9187);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (4, 'Washington', 'Seattle', 'Eliot', '98104', 5014);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (5, 'Mississippi', 'Gulfport', 'Michigan', '39505', 76);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (6, 'Missouri', 'Kansas City', 'Merrick', '64179', 23412);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (7, 'North Dakota', 'Bismarck', 'Magdeline', '58505', 75093);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (8, 'Colorado', 'Aurora', 'Delladonna', '80045', 8144);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (9, 'Washington', 'Tacoma', 'Mockingbird', '98424', 709);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (10, 'New York', 'New York City', 'Annamark', '10292', 115);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (11, 'New York', 'Rochester', 'Arkansas', '14646', 5471);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (12, 'Wisconsin', 'Madison', 'Sauthoff', '53779', 948);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (13, 'Tennessee', 'Nashville', 'Eastlawn', '37245', 7859);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (14, 'Connecticut', 'Stamford', 'Hoffman', '06912', 4857);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (15, 'California', 'Modesto', 'Rutledge', '95397', 9);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (16, 'Florida', 'Miami', 'Aberg', '33129', 58792);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (17, 'Illinois', 'Rockford', 'Union', '61110', 9);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (18, 'North Carolina', 'Raleigh', 'Green', '27635', 37);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (19, 'District of Columbia', 'Washington', 'Mayer', '20244', 9024);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (20, 'Missouri', 'Saint Louis', 'Hanover', '63169', 16138);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (21, 'Maryland', 'Bethesda', 'Meadow Vale', '20816', 9);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (22, 'District of Columbia', 'Washington', 'Schiller', '20392', 1);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (23, 'Pennsylvania', 'Philadelphia', 'Pennsylvania', '19160', 4064);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (24, 'Kentucky', 'Louisville', 'Vernon', '40298', 781);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (25, 'Iowa', 'Des Moines', 'Gerald', '50362', 56486);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (26, 'California', 'North Hollywood', 'Algoma', '91616', 81885);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (27, 'Washington', 'Spokane', 'Almo', '99220', 43710);
