INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (1, 'FastTrack Express', 'ddaffewfew', 9);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (2, 'SwiftShip', 'Sprain of calcaneofibular ligament of right ankle, sequela', 13.9);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (3, 'RapidCargo', 'Unsp injury of unspecified middle and inner ear, subs encntr', 2.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (4, 'SpeedyDeliver', 'Nondisp fx of olecran pro w intartic extn unsp ulna, 7thB', 7.9);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (5, 'QuickDispatch', 'Other meniscus derangements, unsp meniscus, right knee', 15.9);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (6, 'TurboTransit', 'Breakdown (mechanical) of implnt elec nstim, generator', 8.9);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (7, 'ExpressMovers', 'Corrosion of unsp degree of left shoulder, subs encntr', 12.1);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (8, 'LightningLogistics', 'Other instability, ankle and foot', 3.5);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (9, 'SpeedwayShipping', 'Mature T/NK-cell lymphomas, unsp, intrapelvic lymph nodes', 7.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (10, 'RapidConnect', 'Oth spon disrupt of anterior cruciate ligament of right knee', 17.2);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (11, 'SwiftHaul', 'Gestational diabetes mellitus in childbirth, unsp control', 7.4);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (12, 'InstantDelivery', 'Medial dislocation of left ulnohumeral joint, subs encntr', 7.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (13, 'RapidRoute', 'Nondisp oblique fx shaft of l rad, 7thJ', 16.3);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (14, 'ExpressLink', 'Acquired absence of unspecified shoulder', 9);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (15, 'QuickShip', 'Physeal arrest, humerus, unspecified', 15.9);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (16, 'SpeedyFreight', 'Puncture wound with foreign body of unsp shoulder, sequela', 14.9);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (17, 'TurboCargo', 'Prsn outsd 3-whl mv inj in clsn w statnry obj nontraf, sqla', 10.5);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (18, 'VelocityExpress', 'Nondisp fx of medial phalanx of r mid fngr, init for opn fx', 12.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (19, 'FastLaneLogistics', 'Colles'' fx left rad, subs for opn fx type 3A/B/C w nonunion', 15.9);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (20, 'RapidShip', 'Contusion of right ear, subsequent encounter', 17.3);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (21, 'SwiftTrans', 'Lac w fb of lower back and pelvis w penet retroperiton, subs', 2.4);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (22, 'ExpressSpeed', 'Osteitis condensans, shoulder', 16.5);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (23, 'QuickMove', 'Unsp inj intrinsic musc/fasc/tend r mid finger at wrs/hnd lv', 10);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (24, 'SpeedyDispatch', 'Adhes due to fb acc left in body fol unsp procedure, sequela', 14.7);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (25, 'RapidLogistics', 'Puncture wound with foreign body of left wrist', 3.2);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (26, 'SwiftDelivery', 'Nondisp spiral fx shaft of r femr, 7thC', 3.2);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (27, 'LightningExpress', 'Nondisp suprcndl fx w intrcndl extn low end r femr, 7thR', 13.3);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (28, 'SpeedwayLogistics', 'Toxic effect of harmful algae and algae toxins, undet, subs', 7.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (29, 'TurboTransport', 'Wear of artic bearing surface of internal prosth l hip jt', 16.9);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (30, 'FastTrackShipping', 'Corros first deg of shldr/up lmb, ex wrs/hnd unsp site, subs', 4.2);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (31, 'RapidConnect', 'Unsp injury of intrinsic msl/tnd at ank/ft level, right foot', 19.3);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (32, 'ExpressMovers', 'Nondisp fx of neck of MC bone, subs for fx w nonunion', 16.3);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (33, 'QuickTransit', 'Colles'' fracture of unsp radius, subs for clos fx w malunion', 13.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (34, 'SpeedyDeliver', 'Toxic effect of contact w venomous frog, accidental, init', 19.4);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (35, 'SwiftCargo', '2-part nondisp fx of surg nk of unsp humer, 7thG', 12.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (36, 'LightningLogistics', 'Oth fracture of T9-T10 vertebra, subs for fx w nonunion', 16);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (37, 'RapidRoute', 'Adverse effect of local astringents/detergents, subs', 19.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (38, 'ExpressLink', 'Other spacecraft accident injuring occupant, init encntr', 13.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (39, 'SpeedyShip', 'Poisoning by expectorants, intentional self-harm, sequela', 4.1);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (40, 'QuickHaul', 'Unsp inj unsp musc/tend at lower leg level, left leg, subs', 5.1);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (41, 'TurboDelivery', 'Medial dislocation of left ulnohumeral joint', 5.9);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (42, 'VelocityExpress', 'Unsp superficial injury of left ring finger, subs encntr', 11.4);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (43, 'FastLaneTransit', 'Other specified disorders of synovium and tendon', 12);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (44, 'RapidShip', 'Corrosion of unsp degree of unsp scapular region, subs', 4);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (45, 'SwiftFreight', 'Other hypertrophic disorders of the skin', 4.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (46, 'InstantConnect', 'Multiple endocrine neoplasia [MEN] syndromes', 9.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (47, 'SpeedyLogistics', 'Drug/chem diab w prolif diab rtnop w trctn dtch macula,l eye', 11.5);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (48, 'TurboTrans', 'Disp fx of lateral cuneiform of l ft, 7thD', 18);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (49, 'RapidSpeed', 'Disp fx of dist phalanx of r mid fngr, 7thD', 13.2);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (50, 'ExpressDispatch', 'Separation of retinal layers', 14.3);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (51, 'QuickShip', 'Central European tick-borne encephalitis', 6.4);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (52, 'SpeedyRoute', 'Unspecified subluxation of left sternoclavicular joint', 10.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (53, 'RapidLogistics', 'Unspecified acquired deformity of forearm', 1.1);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (54, 'SwiftDelivery', 'Other recurrent atlantoaxial dislocation', 10.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (55, 'LightningExpress', 'Oth foreign object in pharynx causing oth injury, init', 8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (56, 'SpeedwayLogistics', 'Driver of bus injured in collision w hv veh nontraf, init', 10.1);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (57, 'TurboTransport', 'Laceration without foreign body, right lower leg, sequela', 16);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (58, 'FastTrackShipping', 'Disorders of carnitine metabolism', 7.4);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (59, 'RapidConnect', 'Corrosion of third degree of left lower leg, init encntr', 3.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (60, 'ExpressMovers', 'Superficial foreign body of r frnt wl of thorax, sequela', 17.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (61, 'QuickTransit', 'Mech compl of intraperitoneal dialysis catheter, subs encntr', 7.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (62, 'SpeedyDeliver', 'Abrasion, right lesser toe(s), initial encounter', 9.1);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (63, 'SwiftCargo', 'Lacerat great saphenous at low leg level, left leg, sequela', 14.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (64, 'LightningLogistics', 'Corrosion of unsp deg mult sites of left wrs/hnd, sequela', 12.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (65, 'RapidRoute', 'Abrasion of unsp external genital organs, female, subs', 5.5);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (66, 'ExpressLink', 'Fx femur following insrt ortho implnt/prosth/bone plt', 15.5);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (67, 'QuickMove', 'Laceration of left renal vein, sequela', 13.3);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (68, 'SpeedyDispatch', 'Malignant neoplasm of overlapping sites of oropharynx', 16.3);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (69, 'RapidLogistics', 'Lac w fb of l frnt wl of thorax w penet thor cavity, sequela', 12.2);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (70, 'SwiftDelivery', 'Displ seg fx shaft of ulna, unsp arm, 7thC', 6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (71, 'LightningExpress', 'Occup of pk-up/van inj in clsn w nonmtr veh in traf, init', 11);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (72, 'SpeedwayLogistics', 'Poisoning by centr-acting/adren-neurn-block agnt, undet', 6.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (73, 'TurboTransport', 'Leukoplakia and oth disturb of oral epithelium, inc tongue', 10.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (74, 'FastLaneShipping', 'Contusion of thorax', 11.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (75, 'RapidShip', 'Other cyst of bone, right upper arm', 1.3);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (76, 'SwiftFreight', 'Bitten by duck', 3.4);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (77, 'InstantConnect', 'Corrosion of unsp degree of unspecified foot, subs encntr', 17.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (78, 'SpeedyLogistics', 'Arachnophobia', 1.5);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (79, 'TurboTrans', 'Nondisp transverse fx shaft of humer, unsp arm, 7thP', 1.1);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (80, 'ExpressSpeed', 'Nondisp transverse fx r patella, 7thD', 12.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (81, 'QuickShip', 'Bedroom in boarding-house as place', 15.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (82, 'SpeedyRoute', 'Nondisp dome fracture of unsp talus, subs for fx w nonunion', 6.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (83, 'RapidLogistics', 'Osteonecrosis in diseases classified elsewhere, left forearm', 12.3);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (84, 'SwiftDelivery', 'Oth osteopor w crnt path fx, unsp humer, 7thP', 12.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (85, 'LightningExpress', 'Pnctr w/o fb of unsp external genital organs, male, init', 8.5);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (86, 'SpeedwayLogistics', 'Inflammatory disorders of scrotum', 1.8);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (87, 'TurboTransport', 'Legal intervnt w inj by handgun, law enforc offl inj, subs', 5.2);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (88, 'FastTrackShipping', 'Proc/trtmt not crd out bec pt decision for oth reasons', 4.4);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (89, 'RapidConnect', 'Other injury of uterus, initial encounter', 13.1);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (90, 'ExpressMovers', 'Corrosion of second degree of buttock, subsequent encounter', 16.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (91, 'QuickTransit', 'Military firearm discharge, undetermined intent, subs encntr', 6.4);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (92, 'SpeedyDeliver', 'Age-rel osteopor w crnt path fx, l humer, 7thD', 4.3);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (93, 'SwiftCargo', 'Nondisp seg fx shaft of humerus, unsp arm, init for opn fx', 16.7);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (94, 'LightningLogistics', 'Epidermal thickening, unspecified', 14.2);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (95, 'RapidRoute', 'Disorder of ligament, elbow', 5.6);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (96, 'ExpressLink', 'Postproc seroma of skin, subcu following other procedure', 8.4);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (97, 'SpeedyShip', 'Frostbite with tissue necrosis of left ear, subs encntr', 9.3);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (98, 'QuickHaul', 'Abscess of tendon sheath, lower leg', 20);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (99, 'TurboDelivery', 'Displ transverse fx shaft of unsp tibia, 7thJ', 9.1);
INSERT INTO public."Servizi" (id, nome, descrizione, costo) VALUES (100, 'VelocityExpress', 'Toxic effect of unspecified alcohol, intentional self-harm', 14.3);
