INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (3, 'Alabama', 'Birmingham', 'Cambridge', '35205', 53);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (17, 'Alabama', 'Birmingham', 'Longview', '35290', 52);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (5, 'Alabama', 'Birmingham', 'Carberry', '35231', 6227);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (18, 'Alabama', 'Montgomery', 'Maple', '36195', 80);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (20, 'Alabama', 'Birmingham', 'Nova', '35263', 634);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (26, 'Alabama', 'Anniston', 'Sundown', '36205', 1);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (19, 'Alabama', 'Anniston', 'Mariners Cove', '36205', 55594);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (23, 'Alabama', 'Mobile', 'Rusk', '36689', 15);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (27, 'Alabama', 'Tuscaloosa', 'Talmadge', '35487', 9);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (7, 'Alabama', 'Birmingham', 'Darwin', '35215', 8);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (25, 'Alabama', 'Montgomery', 'Springs', '36125', 26);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (22, 'Alabama', 'Huntsville', 'Petterle', '35895', 44177);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (24, 'Alabama', 'Anniston', 'Sommers', '36205', 8848);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (2, 'Alabama', 'Mobile', 'Burrows', '36670', 41);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (16, 'Alabama', 'Montgomery', 'Kenwood', '36109', 789);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (13, 'Alabama', 'Birmingham', 'Green', '35254', 6212);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (1, 'Alabama', 'Birmingham', 'Bultman', '35242', 226);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (9, 'Alabama', 'Mobile', 'Derek', '36610', 3208);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (10, 'Alabama', 'Mobile', 'Di Loreto', '36610', 4103);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (12, 'Alabama', 'Mobile', 'Goodland', '36616', 2);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (15, 'Alabama', 'Birmingham', 'Harbort', '35244', 56249);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (6, 'Alabama', 'Birmingham', 'Dapin', '35215', 704);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (8, 'Alabama', 'Huntsville', 'Derek', '35805', 2190);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (11, 'Alabama', 'Montgomery', 'Fairfield', '36119', 4);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (14, 'Alabama', 'Anniston', 'Gulseth', '36205', 936);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (21, 'Alabama', 'Birmingham', 'Pepper Wood', '35242', 83);
INSERT INTO public."Filiale" (id, regione, città, via, provincia, numero_civico) VALUES (4, 'Alabama', 'Tuscaloosa', 'Cambridge', '35487', 82);
