INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (2, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (2, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (2, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (14, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (7, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (36, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (17, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (38, 1, 'FastTrack Express', 9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (39, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (40, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (41, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (18, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (43, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (44, 2, 'SwiftShip', 13.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (45, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (46, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (47, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (8, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (20, 3, 'RapidCargo', 2.8);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (21, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (52, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (3, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (54, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (23, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (24, 4, 'SpeedyDeliver', 7.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (25, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (10, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (4, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (28, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (29, 5, 'QuickDispatch', 15.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (30, 6, 'TurboTransit', 8.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (14, 6, 'TurboTransit', 8.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (2, 6, 'TurboTransit', 8.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (7, 6, 'TurboTransit', 8.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (36, 6, 'TurboTransit', 8.9);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (17, 7, 'ExpressMovers', 12.1);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (38, 7, 'ExpressMovers', 12.1);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (39, 7, 'ExpressMovers', 12.1);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (40, 7, 'ExpressMovers', 12.1);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (41, 7, 'ExpressMovers', 12.1);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (18, 8, 'LightningLogistics', 3.5);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (43, 8, 'LightningLogistics', 3.5);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (44, 8, 'LightningLogistics', 3.5);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (45, 8, 'LightningLogistics', 3.5);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (46, 8, 'LightningLogistics', 3.5);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (47, 9, 'SpeedwayShipping', 7.6);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (8, 9, 'SpeedwayShipping', 7.6);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (20, 9, 'SpeedwayShipping', 7.6);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (21, 9, 'SpeedwayShipping', 7.6);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (52, 10, 'RapidConnect', 17.2);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (3, 10, 'RapidConnect', 17.2);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (54, 10, 'RapidConnect', 17.2);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (23, 10, 'RapidConnect', 17.2);
INSERT INTO public."Spedizione_Economica_Servizi" (tracking, id, nome_servizio, costo) VALUES (24, 10, 'RapidConnect', 17.2);
